[project]
name = "marimo-flow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "marimo>=0.9.12",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.6.9",
]
